'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.4927
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o vuelva a generar su proyecto de VS.
    '''<summary>
    '''  Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Teatro.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _1day() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1day", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _5days() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5days", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _date() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("date", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _exit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _stop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property add_user() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_user", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property application_add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("application_add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property application_form_delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("application_form_delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property apply() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("apply", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property back1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("back1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property back2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("back2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_ok() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_ok", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_ok1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_ok1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property calc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("calc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CASHB01C() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CASHB01C", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property chart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CREDT01K() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CREDT01K", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CREDT01K1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CREDT01K1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CREDT03B() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CREDT03B", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cursos_de_guitarra_electrica_y_acustica_6c8d656a_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cursos-de-guitarra-electrica-y-acustica_6c8d656a_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property date_edit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("date_edit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property date_go() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("date_go", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property delete_user() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete_user", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property edit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property email_go() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("email_go", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property filesave() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("filesave", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FondoTeatro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FondoTeatro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property forward() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forward", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property forward1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forward1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property forward2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forward2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icono() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icono", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property kcalc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kcalc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property kcmmidi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kcmmidi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property key() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("key", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property key_add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("key_add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property key1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("key1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Login() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Login", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Logo_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Logo 2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logo_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo 3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property money() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("money", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property money_add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("money_add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property money_delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("money_delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property money_dollar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("money_dollar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property page() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property page_edit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page_edit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property page_go() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page_go", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property password() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("password", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property password1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("password1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property reload3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reload3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property report_go() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("report_go", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property search() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("search", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property today() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("today", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tooloptions() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tooloptions", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property user_add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user_add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property user_delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user_delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property user_edit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user_edit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property user_properties() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user_properties", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
